site_name: numclassify
site_description: The most comprehensive Python number classification library - 3000+ types
site_url: https://aratrikghosh2011-tech.github.io/numclassify/
repo_url: https://github.com/aratrikghosh2011-tech/numclassify
repo_name: aratrikghosh2011-tech/numclassify

theme:
  name: material
  palette:
    primary: custom
    accent: custom
    scheme: slate
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy

extra_css:
  - extra/saffron.css

nav:
  - Home: index.md
  - API Reference: api.md
  - CLI: cli.md
  - Changelog: ../CHANGELOG.md
  - Playground: playground.html

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - tables
